<?php

/**
 * Excel Helper
 *
 * A helper file for generating Excel exports using PhpSpreadsheet
 */

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\RichText\RichText;

if (!function_exists('export_to_excel')) {
    /**
     * Export data to Excel file
     *
     * @param string $filename The name of the file to be generated (without extension)
     * @param array $headers Column headers
     * @param array $data Array of data to be exported
     * @param string $sheetTitle Title of the worksheet (optional)
     * @param array $columnWidths Array of column widths (optional)
     * @param bool $autoFilter Whether to enable auto filter for the header row (optional)
     * @param bool $download Whether to download the file or save it locally (optional)
     * @param string $savePath Path to save the file if not downloading (optional)
     * @return string|bool Returns file path if saved locally, true if downloaded, false on failure
     */    function export_to_excel(
        string $filename,
        array $headers,
        array $data,
        string $sheetTitle = 'Sheet1',
        array $columnWidths = [],
        bool $autoFilter = true,
        bool $download = true,
        string $savePath = WRITEPATH . 'uploads/excel/'
    ) {
        log_message('debug', 'Starting export_to_excel function: ' . $filename . ' with ' . count($data) . ' rows of data');
        
        // Verify that each row is a simple array with scalar values only
        foreach ($data as $rowIndex => $row) {
            if (!is_array($row)) {
                $type = gettype($row);
                log_message('error', "Row {$rowIndex} is not an array (type: {$type})");
                throw new \Exception("Invalid data format: Row {$rowIndex} is not an array");
            }
            
            foreach ($row as $colIndex => $value) {
                if (!is_scalar($value) && !is_null($value)) {
                    $type = gettype($value);
                    log_message('error', "Non-scalar value at row {$rowIndex}, column {$colIndex} (type: {$type})");
                    $data[$rowIndex][$colIndex] = "[Invalid: {$type}]";
                }
            }
        }
        log_message('debug', 'Validated that all data is in simple array format with scalar values only');
        
        // Clean all output buffers at the beginning to prevent any content before Excel data
        while (ob_get_level()) {
            ob_end_clean();
        }
        log_message('debug', 'Cleaned output buffers');

        // Start a new output buffer to ensure clean output
        ob_start();
        log_message('debug', 'Started new output buffer');

        try {            // Store the original error reporting level and turn off all error reporting
            $oldErrorReporting = error_reporting();
            error_reporting(0);
            log_message('debug', 'Error reporting turned off for Excel generation');

            // Create new Spreadsheet object
            log_message('debug', 'Creating new PhpSpreadsheet object');
            $spreadsheet = new Spreadsheet();
            log_message('debug', 'PhpSpreadsheet object created successfully');

            // Set document properties
            $spreadsheet->getProperties()
                ->setCreator('YBB Admin System')
                ->setLastModifiedBy('YBB Admin System')
                ->setTitle($filename)
                ->setSubject($filename)
                ->setDescription('Document generated by YBB Admin System')
                ->setKeywords('office excel php')
                ->setCategory('Export Data');            // Get active sheet
            $sheet = $spreadsheet->getActiveSheet();
            $sheet->setTitle($sheetTitle);
            log_message('debug', 'Created worksheet with title: ' . $sheetTitle);

            // Set headers in first row - starting at A1
            $col = 'A';
            log_message('debug', 'Adding ' . count($headers) . ' header columns');
            foreach ($headers as $header) {
                $sheet->setCellValue($col . '1', $header);
                $col++;
            }
            log_message('debug', 'Headers added to worksheet, last column: ' . chr(ord($col) - 1) . '1');            // Style the header row
            $lastCol = chr(64 + count($headers)); // ASCII 65 is 'A'
            if ($lastCol > 'Z') {
                // Handle columns beyond Z (AA, AB, etc.)
                $lastCol = 'A' . chr(64 + (count($headers) - 26));
            }
            log_message('debug', 'Styling header row from A1 to ' . $lastCol . '1');

            $sheet->getStyle('A1:' . $lastCol . '1')->applyFromArray([
                'font' => [
                    'bold' => true,
                    'color' => ['rgb' => 'FFFFFF'],
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '4472C4'],
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                    ],
                ],
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ]);            // Set filter for headers if requested
            if ($autoFilter) {
                $sheet->setAutoFilter('A1:' . $lastCol . '1');
                log_message('debug', 'Set auto filter on headers');
            }

            // Set column widths if provided
            if (!empty($columnWidths)) {
                $col = 'A';
                log_message('debug', 'Setting column widths for ' . count($columnWidths) . ' columns');
                foreach ($columnWidths as $width) {
                    $sheet->getColumnDimension($col)->setWidth($width);
                    $col++;
                }
                log_message('debug', 'Column widths set successfully');
            }        // Add data
            $row = 2;
            log_message('debug', 'Starting to add data rows to Excel, ' . count($data) . ' rows to process');
            
            // Debug the incoming data
            debug_to_file($data, 'Input Data for Excel Export');
            
            try {
                foreach ($data as $rowData) {
                    $col = 'A';
                    
                    // Debug each row
                    debug_to_file($rowData, 'Processing Row Data');
                    log_message('debug', 'Processing row ' . $row . ' with ' . count($rowData) . ' cells');
                      foreach ($rowData as $cellValue) {
                        try {
                            // Log problematic data types for debugging
                            if (!is_scalar($cellValue) && !is_null($cellValue)) {
                                $type = is_array($cellValue) ? 'array' : (is_object($cellValue) ? 'object' : gettype($cellValue));
                                log_message('debug', "Cell at " . $col . $row . " contains non-scalar data: " . $type);
                                debug_to_file($cellValue, 'Non-scalar Cell Value at ' . $col . $row);
                            }
                            
                            // Handle binary data (resources or binary strings)
                            if (is_resource($cellValue)) {
                                log_message('warning', "Resource found in cell " . $col . $row . ". Converting to string.");
                                $safeValue = "[Resource of type: " . get_resource_type($cellValue) . "]";
                            }
                            // Handle array or object values
                            else if (is_array($cellValue) || is_object($cellValue)) {
                                log_message('debug', "Converting complex data in cell " . $col . $row . " to JSON");
                                $safeValue = json_encode($cellValue, JSON_UNESCAPED_UNICODE);
                                if ($safeValue === false) {
                                    // Handle JSON encoding error
                                    $safeValue = "[Complex data - cannot encode]";
                                    $errorMsg = json_last_error_msg();
                                    log_message('error', "JSON encoding error in cell " . $col . $row . ": " . $errorMsg);
                                    debug_to_file(json_last_error_msg(), 'JSON Encoding Error at ' . $col . $row);
                                }
                            } else {
                                // Clean scalar values
                                $safeValue = clean_for_excel($cellValue);
                            }
                              // Check if value is too large for Excel
                            if (is_string($safeValue) && strlen($safeValue) > 32767) { // Excel's cell character limit
                                log_message('warning', "Cell value at " . $col . $row . " exceeds Excel limit. Truncating " . strlen($safeValue) . " chars");
                                $safeValue = substr($safeValue, 0, 32700) . "... [truncated]";
                            }
                            
                            // Handle cell formatting based on content type or explicit formatting
                            $sheet->setCellValue($col . $row, $safeValue);
                            $col++;
                        } catch (\Throwable $e) { // Use Throwable to catch both Exception and Error objects
                            $errorMsg = $e->getMessage();
                            $errorClass = get_class($e);
                            $errorTrace = $e->getTraceAsString();
                            
                            debug_to_file([
                                'message' => $errorMsg,
                                'class' => $errorClass,
                                'trace' => $errorTrace
                            ], 'Cell Processing Error at ' . $col . $row);
                            
                            log_message('error', "Error processing Excel cell at {$col}{$row}: {$errorClass}: {$errorMsg}");
                            
                            // Skip this cell if there's an error
                            $sheet->setCellValue($col . $row, '[ERROR]');
                            $col++;
                        }
                    }
                    $row++;
                }
                log_message('debug', 'Finished adding ' . ($row - 2) . ' data rows to Excel');
            } catch (\Exception $e) {
                debug_to_file($e->getMessage(), 'Row Processing Error');
                log_message('error', 'Error processing Excel row: ' . $e->getMessage());
                log_message('error', 'Exception trace: ' . $e->getTraceAsString());
                throw $e; // Re-throw to be caught by the outer catch block
            }            // Create Excel writer
            log_message('debug', 'Creating Excel writer (Xlsx)');
            $writer = new Xlsx($spreadsheet);

            // Enable auto-sizing for columns where a width wasn't specified
            if (count($columnWidths) < count($headers)) {
                log_message('debug', 'Setting auto-size for columns without specified widths');
                $col = chr(65 + count($columnWidths)); // Start from the next column after those with specified widths
                while (ord($col) <= (64 + count($headers))) {
                    $sheet->getColumnDimension($col)->setAutoSize(true);
                    $col = chr(ord($col) + 1);
                }
                log_message('debug', 'Auto-sized columns from ' . chr(65 + count($columnWidths)) . ' to ' . chr(64 + count($headers)));
            }            // Ensure the directory exists
            if (!is_dir($savePath) && $savePath !== '' && !$download) {
                log_message('debug', 'Creating directory path: ' . $savePath);
                mkdir($savePath, 0755, true);
            }

            // Set the file path
            $filePath = $savePath . $filename . '.xlsx';
            log_message('debug', 'Excel file path set to: ' . $filePath);
            
            // Download or save file
            if ($download) {
                log_message('debug', 'Starting Excel download process');
                // Headers may already be sent at this point - check and log if they are
                if (headers_sent($file, $line)) {
                    log_message('error', "Headers already sent in $file:$line when trying to download Excel file");
                    log_message('error', "Headers sent from: $file at line: $line");
                    return false;
                }
                log_message('debug', 'No headers sent yet, proceeding with download');                // Clear all output buffers first
                while (ob_get_level()) {
                    ob_end_clean();
                }
                
                // Set download headers - be very specific with MIME type
                log_message('debug', 'Setting headers for Excel download');
                header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
                header('Content-Disposition: attachment; filename="' . $filename . '.xlsx"');
                header('Cache-Control: no-cache, no-store, must-revalidate');
                header('Pragma: no-cache');
                header('Expires: 0');               
                header('Content-Transfer-Encoding: binary');
                log_message('debug', 'Download headers set successfully');

                // Use a safe approach to save file to output
                try {
                    debug_to_file('Starting file download process', 'Download Process');
                    log_message('debug', 'Starting Excel download process using temporary file');
                    
                    // Use a temporary file first to avoid memory issues with large files
                    $tempFile = tempnam(sys_get_temp_dir(), 'excel_export_');
                    log_message('debug', 'Created temporary file: ' . $tempFile);
                    $writer->save($tempFile);
                    log_message('debug', 'Excel data saved to temporary file successfully');
                      debug_to_file('Excel file saved to temp location: ' . $tempFile, 'Download Process');

                    // Get file size for Content-Length header
                    $fileSize = filesize($tempFile);
                    header('Content-Length: ' . $fileSize);
                    log_message('debug', 'Set Content-Length header: ' . $fileSize . ' bytes');
                      // Clear all output buffers completely to ensure clean output
                    while (ob_get_level()) {
                        ob_end_clean();
                    }
                    // Start a fresh output buffer
                    ob_start();
                    
                    log_message('debug', 'All output buffers cleaned for file download');
                    debug_to_file('About to send file to browser, size: ' . $fileSize, 'Download Process');
                    log_message('debug', 'Sending Excel file to browser, size: ' . $fileSize . ' bytes');
                    
                    // Output the file to the browser
                    readfile($tempFile);
                    
                    // Get buffer contents and clean it
                    $content = ob_get_clean();
                    
                    // Send the file contents without any other output
                    echo $content;
                    log_message('debug', 'File sent to browser via clean buffer');
                    
                    // Flush output to browser
                    flush();

                    // Remove the temp file
                    @unlink($tempFile);
                    log_message('debug', 'Temporary file removed');
                    
                    debug_to_file('Download completed successfully', 'Download Process');
                    log_message('debug', 'Excel download process completed successfully');                } catch (\Throwable $e) {
                    // Log any errors that occur during saving
                    log_message('error', 'Excel download process failed: ' . $e->getMessage());
                    log_message('error', 'Error file: ' . $e->getFile() . ' line: ' . $e->getLine());
                    log_message('error', 'Error trace: ' . $e->getTraceAsString());
                    
                    $errorDetails = [
                        'message' => $e->getMessage(),
                        'code' => $e->getCode(),
                        'file' => $e->getFile(),
                        'line' => $e->getLine(),
                        'trace' => $e->getTraceAsString()
                    ];
                      log_message('error', 'Failed to save Excel file to output: ' . $e->getMessage());
                    debug_to_file($errorDetails, 'Excel Download Exception');

                    // Make sure we can send a clean response
                    if (ob_get_length()) {
                        log_message('debug', 'Cleaning output buffer to prepare error response');
                        ob_clean();
                    }
                    
                    // Return a proper JSON error response to avoid 'Unexpected end of JSON input' errors
                    log_message('debug', 'Setting headers for JSON error response');
                    header('Content-Type: application/json');
                    $errorResponse = [
                        'error' => 'Failed to generate Excel file: ' . $e->getMessage(),
                        'details' => $errorDetails,
                        'status' => 'failed'
                    ];
                    log_message('debug', 'Sending JSON error response');
                    echo json_encode($errorResponse);
                }                // Restore error reporting
                error_reporting($oldErrorReporting);
                log_message('debug', 'Restored original error reporting level');

                // Exit to prevent additional output that might corrupt the file
                log_message('debug', 'Exiting process after Excel download completion');
                exit;            } else {
                // Save to disk
                log_message('debug', 'Saving Excel file to disk at: ' . $filePath);
                $writer->save($filePath);
                log_message('debug', 'Excel file saved successfully to: ' . $filePath);
                return $filePath;
            }
        } catch (\Throwable $e) {
            // Log detailed error information
            log_message('error', 'Excel generation failed: ' . $e->getMessage());
            log_message('error', 'Error occurred in file: ' . $e->getFile() . ' line: ' . $e->getLine());
            log_message('error', 'Error trace: ' . $e->getTraceAsString());
            
            $errorDetails = [
                'message' => $e->getMessage(),
                'code' => $e->getCode(),
                'file' => $e->getFile(),
                'line' => $e->getLine(),
                'trace' => $e->getTraceAsString()
            ];
            
            log_message('error', 'Excel export error: ' . $e->getMessage());
            debug_to_file($errorDetails, 'Excel Export Exception');            // If headers have not been sent yet and this is a download request, 
            // send a proper JSON error response
            if (!headers_sent() && $download) {
                log_message('debug', 'Preparing JSON error response for failed Excel generation');
                // Clear any output that might have been started
                if (ob_get_length()) {
                    log_message('debug', 'Cleaning output buffer before sending error response');
                    ob_clean();
                }
                
                log_message('debug', 'Setting JSON content type header for error response');
                header('Content-Type: application/json');                $errorResponse = [
                    'error' => 'Excel export error: ' . $e->getMessage(),
                    'details' => $errorDetails,
                    'status' => 'failed'
                ];
                log_message('debug', 'Sending JSON error response: ' . json_encode($errorResponse));
                echo json_encode($errorResponse);
                exit;
            }
            log_message('debug', 'Excel export failed, returning false');
            return false;
        }
    }
}

if (!function_exists('format_excel_date')) {
    /**
     * Format date for Excel
     *
     * @param string|null $date Date string
     * @param string $format Output format (default: 'd/m/Y')
     * @return string Formatted date or empty string if null
     */
    function format_excel_date($date, string $format = 'd/m/Y'): string
    {
        if (empty($date)) {
            return '';
        }

        try {
            return date($format, strtotime($date));
        } catch (\Exception $e) {
            return '';
        }
    }
}

if (!function_exists('format_excel_currency')) {
    /**
     * Format number as currency for Excel
     *
     * @param float|int|string $number Number to format
     * @param string $prefix Currency prefix (default: 'Rp ')
     * @return string Formatted currency
     */
    function format_excel_currency($number, string $prefix = 'Rp '): string
    {
        return $prefix . number_format((float) $number, 0, ',', '.');
    }
}

if (!function_exists('debug_to_file')) {
    /**
     * Debug function to log data to file
     * 
     * @param mixed $data Data to log
     * @param string $label Optional label
     * @return void
     */
    function debug_to_file($data, $label = '') {
        $file = WRITEPATH . 'logs/excel_debug.log';
        
        // Add timestamp, label and info about data type
        $content = date('Y-m-d H:i:s') . " - " . $label . " (Type: " . gettype($data) . "):\n";
        
        // Handle all types of data properly
        if (is_null($data)) {
            $content .= "NULL\n";
        } elseif (is_scalar($data)) {
            // Handle string, number, boolean
            $content .= "Value: " . $data . "\n";
            if (is_string($data) && strlen($data) > 100) {
                $content .= "Length: " . strlen($data) . " chars\n";
                // Include excerpt of long strings
                $content .= "Preview: " . substr($data, 0, 100) . "...\n";
            }
        } elseif (is_array($data)) {
            // For arrays, note the size and convert to string representation
            $content .= "Array with " . count($data) . " elements\n";
            try {
                // Use json_encode with prettify for arrays to avoid excessive depth in print_r
                if (count($data) < 50) {
                    // For small arrays, include all content
                    $content .= json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n";
                } else {
                    // For large arrays, show a sample
                    $content .= "Sample of first 20 items:\n";
                    $content .= json_encode(array_slice($data, 0, 20, true), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n";
                }
            } catch (\Exception $e) {
                // Fall back to print_r with limited depth if JSON encode fails
                $content .= "Error encoding array to JSON: " . $e->getMessage() . "\n";
                $content .= print_r(array_slice($data, 0, 10, true), true) . "...\n";
            }
        } elseif (is_object($data)) {
            // For objects, note the class and try to convert to array first
            $content .= "Object of class " . get_class($data) . "\n";
            try {
                // Try to convert to array first
                if (method_exists($data, 'toArray')) {
                    $array = $data->toArray();
                    $content .= json_encode($array, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n";
                } else {
                    // Otherwise use json_encode directly on the object
                    $content .= json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n";
                }
            } catch (\Exception $e) {
                // Fall back to a basic inspection
                $content .= "Error encoding object to JSON: " . $e->getMessage() . "\n";
                $content .= "Object properties: " . print_r(get_object_vars($data), true) . "\n";
            }
        } else {
            // Resource or other type
            $content .= "Unhandled data type\n";
        }
        
        $content .= "\n" . str_repeat('-', 50) . "\n\n";
        
        // Ensure directory exists
        $dir = dirname($file);
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }
        
        file_put_contents($file, $content, FILE_APPEND);
        
        // Also log to system log
        log_message('debug', 'Excel debug data written to file: ' . $label);
    }
}

if (!function_exists('clean_for_excel')) {
    /**
     * Clean text for Excel export to prevent corruption
     *
     * @param string $text Text to clean
     * @return string Cleaned text
     */
    function clean_for_excel($text): string
    {
        if (empty($text)) {
            return '';
        }

        // Check if it's a string, otherwise convert to string
        if (!is_string($text)) {
            $text = (string)$text;
        }

        // If text is too long, truncate it (prevents memory issues with large rich text)
        if (strlen($text) > 32000) { // Excel cell limit is around 32,767 characters
            $text = substr($text, 0, 32000) . '...';
        }

        // Handle rich text from Quill editor or HTML content
        if (preg_match('/<[^>]+>/', $text)) {
            // Strip HTML tags if content appears to be HTML
            $text = strip_tags($text);
        }        // Try to convert to UTF-8 if not already
        try {
            if (!mb_check_encoding($text, 'UTF-8')) {
                log_message('debug', 'Text not in UTF-8, detecting encoding...');
                $detected = mb_detect_encoding($text, ['UTF-8', 'ASCII', 'ISO-8859-1', 'Windows-1252'], true);
                log_message('debug', 'Detected encoding: ' . ($detected ?: 'unknown') . ', converting to UTF-8');
                $text = mb_convert_encoding($text, 'UTF-8', $detected ?: 'Windows-1252');
            }
        } catch (\Exception $e) {
            log_message('error', 'Encoding conversion error: ' . $e->getMessage());
            // If encoding detection fails, try a simple Windows-1252 to UTF-8 conversion
            $text = mb_convert_encoding($text, 'UTF-8', 'Windows-1252');
            log_message('debug', 'Fallback conversion from Windows-1252 to UTF-8 applied');
        }

        // Remove control characters that can cause Excel corruption
        $text = preg_replace('/[\x00-\x09\x0B\x0C\x0E-\x1F\x7F]/', '', $text);

        // Remove or replace problematic Unicode characters
        $text = preg_replace('/[\x{FFFE}\x{FFFF}\x{202E}\x{200E}\x{200F}]/u', '', $text);

        // Replace common problematic sequences that might be in JSON
        $text = str_replace(['\n', '\r', '\t', '\"'], [' ', ' ', ' ', '"'], $text);

        // Clean up any residual JSON or HTML entities
        $text = html_entity_decode($text, ENT_QUOTES, 'UTF-8');

        // Replace zero-width spaces and other invisible characters that can cause issues
        $text = str_replace(["\u{200B}", "\u{200C}", "\u{200D}", "\u{FEFF}"], '', $text);        // Remove emojis and special characters that Excel might not handle well
        $originalLength = strlen($text);
        $text = preg_replace('/[\x{10000}-\x{10FFFF}]/u', '', $text);
        if ($originalLength != strlen($text)) {
            log_message('debug', 'Removed emojis and special characters');
        }

        // Final check for any problematic JSON sequences or escape characters
        $text = str_replace(['\u', '\\\\', '\\n', '\\r', '\\t'], ['', '\\', ' ', ' ', ' '], $text);

        // Trim whitespace
        $text = trim($text);
        
        log_message('debug', 'Final cleaned text length: ' . strlen($text));
        return $text;
    }
}
